// frontend-react/src/components/Navigation.tsx
import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Leaf, Trophy, Award, Home, Shield, TrendingUp, Building, ShoppingBag, Wallet, Menu, X, LogIn, UserPlus } from 'lucide-react';
import { ConnectWallet } from './ConnectWallet';
import { useUser } from '../contexts/UserContext';
import { cn } from '../lib/utils';

export function Navigation() {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const location = useLocation();
    const navigate = useNavigate();
    const { isAuthenticated, logout, user } = useUser();

    // Base navigation items
    const allNavItems = [
        { href: "/", label: "Dashboard", icon: Home, roles: ['COMPANY', 'VERIFIER', 'AUDITOR', 'ADMIN'] },
        { href: "/actions", label: "Eco Actions", icon: Leaf, roles: ['COMPANY', 'VERIFIER', 'AUDITOR', 'ADMIN'] },
        { href: "/companies", label: "Companies", icon: Building, roles: ['COMPANY', 'VERIFIER', 'AUDITOR', 'ADMIN'] },
        { href: "/marketplace", label: "Marketplace", icon: ShoppingBag, roles: ['COMPANY'] },
        { href: "/staking", label: "Staking", icon: Wallet, roles: ['COMPANY'] },
        { href: "/governance", label: "Governance", icon: Shield, roles: ['COMPANY', 'AUDITOR'] },
        { href: "/analytics", label: "Analytics", icon: TrendingUp, roles: ['COMPANY', 'VERIFIER', 'AUDITOR', 'ADMIN'] },
        { href: "/leaderboard", label: "Leaderboard", icon: Trophy, roles: ['COMPANY', 'VERIFIER', 'AUDITOR', 'ADMIN'] },
        { href: "/badges", label: "NFT Badges", icon: Award, roles: ['COMPANY'] },
    ];

    // Filter navigation items based on user role
    const navItems = isAuthenticated && user?.role
        ? allNavItems.filter(item => item.roles.includes(user.role!.toUpperCase()))
        : allNavItems.filter(item => item.roles.includes('COMPANY')); // Default for unauthenticated

    return (
        <nav className="glass-effect shadow-lg border-b border-secondary-200/50 sticky top-0 z-50 backdrop-blur-xl">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between h-16">
                    <motion.div 
                        className="flex items-center"
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.5 }}
                    >
                        <div className="flex-shrink-0 flex items-center group cursor-pointer">
                            <motion.div
                                whileHover={{ rotate: 360 }}
                                transition={{ duration: 0.6 }}
                            >
                                <Leaf className="h-8 w-8 text-primary-600" />
                            </motion.div>
                            <span className="ml-2 text-xl font-bold gradient-text">
                                GreenLedger
                            </span>
                        </div>
                    </motion.div>

                    <div className="hidden md:flex items-center space-x-2">
                        {navItems.map((item, index) => {
                            const Icon = item.icon;
                            const isActive = location.pathname === item.href;
                            return (
                                <motion.div
                                    key={item.href}
                                    initial={{ opacity: 0, y: -10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: index * 0.05, duration: 0.3 }}
                                >
                                    <Link
                                        to={item.href}
                                        className={cn(
                                            "relative flex items-center px-3 py-2 rounded-lg text-sm font-medium transition-all duration-300",
                                            isActive
                                                ? "text-primary-600 bg-primary-50"
                                                : "text-secondary-700 hover:text-primary-600 hover:bg-primary-50/50"
                                        )}
                                    >
                                        {isActive && (
                                            <motion.div
                                                layoutId="activeTab"
                                                className="absolute inset-0 bg-primary-50 rounded-lg"
                                                initial={false}
                                                transition={{ type: "spring", stiffness: 500, damping: 30 }}
                                            />
                                        )}
                                        <Icon className={cn("h-4 w-4 mr-2 relative z-10", isActive && "text-primary-600")} />
                                        <span className="relative z-10">{item.label}</span>
                                    </Link>
                                </motion.div>
                            );
                        })}
                    </div>

                    <div className="flex items-center space-x-4">
                        <ConnectWallet />
                        
                        {!isAuthenticated ? (
                            <>
                                <motion.div
                                    whileHover={{ scale: 1.05 }}
                                    whileTap={{ scale: 0.95 }}
                                >
                                    <Link
                                        to="/login"
                                        className="hidden md:flex items-center px-4 py-2 rounded-lg text-sm font-medium text-secondary-700 hover:text-primary-600 hover:bg-primary-50/50 transition-all duration-300"
                                    >
                                        <LogIn className="h-4 w-4 mr-2" />
                                        Login
                                    </Link>
                                </motion.div>
                                <motion.div
                                    whileHover={{ scale: 1.05 }}
                                    whileTap={{ scale: 0.95 }}
                                >
                                    <Link
                                        to="/register"
                                        className="hidden md:flex items-center px-4 py-2 rounded-lg text-sm font-medium text-white bg-gradient-to-r from-primary-600 to-emerald-600 hover:from-primary-700 hover:to-emerald-700 shadow-md hover:shadow-lg transition-all duration-300"
                                    >
                                        <UserPlus className="h-4 w-4 mr-2" />
                                        Register
                                    </Link>
                                </motion.div>
                            </>
                        ) : (
                            <motion.div
                                whileHover={{ scale: 1.05 }}
                                whileTap={{ scale: 0.95 }}
                            >
                                <button
                                    onClick={() => {
                                        logout();
                                        navigate('/');
                                    }}
                                    className="hidden md:flex items-center px-4 py-2 rounded-lg text-sm font-medium text-secondary-700 hover:text-red-600 hover:bg-red-50/50 transition-all duration-300"
                                >
                                    <LogIn className="h-4 w-4 mr-2" />
                                    Logout
                                </button>
                            </motion.div>
                        )}

                        <motion.button
                            onClick={() => setIsMenuOpen(!isMenuOpen)}
                            className="md:hidden inline-flex items-center justify-center p-2 rounded-md text-secondary-600 hover:text-secondary-900 hover:bg-secondary-100"
                            aria-label="Toggle mobile menu"
                            whileHover={{ scale: 1.1 }}
                            whileTap={{ scale: 0.9 }}
                        >
                            <AnimatePresence mode="wait">
                                {isMenuOpen ? (
                                    <motion.div
                                        key="close"
                                        initial={{ rotate: -90, opacity: 0 }}
                                        animate={{ rotate: 0, opacity: 1 }}
                                        exit={{ rotate: 90, opacity: 0 }}
                                        transition={{ duration: 0.2 }}
                                    >
                                        <X className="h-6 w-6" />
                                    </motion.div>
                                ) : (
                                    <motion.div
                                        key="menu"
                                        initial={{ rotate: 90, opacity: 0 }}
                                        animate={{ rotate: 0, opacity: 1 }}
                                        exit={{ rotate: -90, opacity: 0 }}
                                        transition={{ duration: 0.2 }}
                                    >
                                        <Menu className="h-6 w-6" />
                                    </motion.div>
                                )}
                            </AnimatePresence>
                        </motion.button>
                    </div>
                </div>
            </div>

            <AnimatePresence>
                {isMenuOpen && (
                    <motion.div
                        className="md:hidden"
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                    >
                        <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white/95 backdrop-blur-lg border-t border-secondary-200">
                            {!isAuthenticated && (
                                <>
                                    <Link
                                        to="/login"
                                        onClick={() => setIsMenuOpen(false)}
                                        className="flex items-center px-3 py-2 rounded-md text-base font-medium text-secondary-700 hover:text-primary-600 hover:bg-primary-50 transition-all duration-200 mb-2"
                                    >
                                        <LogIn className="h-5 w-5 mr-3" />
                                        Login
                                    </Link>
                                    <Link
                                        to="/register"
                                        onClick={() => setIsMenuOpen(false)}
                                        className="flex items-center px-3 py-2 rounded-md text-base font-medium text-white bg-gradient-to-r from-primary-600 to-emerald-600 hover:from-primary-700 hover:to-emerald-700 transition-all duration-200 mb-2"
                                    >
                                        <UserPlus className="h-5 w-5 mr-3" />
                                        Register
                                    </Link>
                                    <div className="border-t border-secondary-200 my-2"></div>
                                </>
                            )}
                            {navItems.map((item, index) => {
                                const Icon = item.icon;
                                const isActive = location.pathname === item.href;
                                return (
                                    <motion.div
                                        key={item.href}
                                        initial={{ opacity: 0, x: -20 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        transition={{ delay: index * 0.05 }}
                                    >
                                        <Link
                                            to={item.href}
                                            onClick={() => setIsMenuOpen(false)}
                                            className={cn(
                                                "flex items-center px-3 py-2 rounded-md text-base font-medium transition-all duration-200",
                                                isActive
                                                    ? "text-primary-600 bg-primary-50"
                                                    : "text-secondary-700 hover:text-primary-600 hover:bg-primary-50"
                                            )}
                                        >
                                            <Icon className="h-5 w-5 mr-3" />
                                            {item.label}
                                        </Link>
                                    </motion.div>
                                );
                            })}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </nav>
    );
}

// frontend/src/lib/components/Navigation.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { Wallet, Leaf, Trophy, Award, Home, Shield } from 'lucide-svelte';
	import { walletService, type WalletState } from '$lib/services/wallet';
	import { authService } from '$lib/services/auth';
	import { UserRole } from '$lib/services/contracts';
	import { onMount, onDestroy } from 'svelte';
	
	let walletState = $state<WalletState>(walletService.getState());
	let authState = $state(authService.getState());
	let isMenuOpen = $state(false);
	let isConnecting = $state(false);
	
	let unsubscribeWallet: (() => void) | null = null;
	let unsubscribeAuth: (() => void) | null = null;
	
	onMount(() => {
		unsubscribeWallet = walletService.subscribe((state) => {
			walletState = state;
		});
		unsubscribeAuth = authService.subscribe((state) => {
			authState = state;
		});
		authService.refreshRole();
	});
	
	onDestroy(() => {
		if (unsubscribeWallet) unsubscribeWallet();
		if (unsubscribeAuth) unsubscribeAuth();
	});
	
	async function connectWallet() {
		isConnecting = true;
		const success = await walletService.connect();
		if (success) {
			// Optionally switch to Sepolia testnet
			await walletService.switchToSepolia();
		}
		isConnecting = false;
	}
	
	async function disconnectWallet() {
		await walletService.disconnect();
	}
	
	const navItems = $derived.by(() => {
		const isVerifier = authState.role === UserRole.ADMIN || authState.role === UserRole.VERIFIER;
		return [
			{ href: '/', label: 'Dashboard', icon: Home },
			{ href: '/actions', label: 'Eco Actions', icon: Leaf },
			{ href: '/leaderboard', label: 'Leaderboard', icon: Trophy },
			{ href: '/badges', label: 'NFT Badges', icon: Award },
			...(isVerifier ? [{ href: '/admin', label: 'Admin', icon: Shield }] : []),
			{ href: '/counter', label: 'Counter', icon: null }
		];
	});
</script>

<nav class="bg-white shadow-lg border-b border-secondary-200">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="flex justify-between h-16">
			<!-- Logo and Brand -->
			<div class="flex items-center">
				<div class="flex-shrink-0 flex items-center">
					<Leaf class="h-8 w-8 text-primary-600" />
					<span class="ml-2 text-xl font-bold text-secondary-900">GreenLedger</span>
				</div>
			</div>
			
			<!-- Desktop Navigation -->
			<div class="hidden md:flex items-center space-x-8">
                {#each navItems as item}
                    <a
                        href={item.href}
                        class="flex items-center px-3 py-2 rounded-md text-sm font-medium transition-colors duration-200
                            {$page.url.pathname === item.href 
                                ? 'text-primary-600 bg-primary-50' 
                                : 'text-secondary-700 hover:text-primary-600 hover:bg-primary-50'}"
                    >
                        {#if item.icon}
                            <item.icon class="h-4 w-4 mr-2" />
                        {/if}
                        {item.label}
                    </a>
                {/each}
			</div>
			
			<!-- Wallet Connection -->
			<div class="flex items-center space-x-4">
				{#if walletState.isConnected}
					<div class="flex items-center space-x-2">
						<div class="bg-primary-100 text-primary-800 px-3 py-1 rounded-full text-sm font-medium">
							{walletService.formatAddress(walletState.address!)}
						</div>
						{#if walletState.balance}
							<div class="text-xs text-secondary-600">
								{parseFloat(walletState.balance).toFixed(4)} ETH
							</div>
						{/if}
						<button
							onclick={disconnectWallet}
							class="text-secondary-600 hover:text-secondary-900 text-sm"
						>
							Disconnect
						</button>
					</div>
				{:else}
					<button
						onclick={connectWallet}
						disabled={isConnecting}
						class="btn-primary flex items-center disabled:opacity-50 disabled:cursor-not-allowed"
					>
						{#if isConnecting}
							<div class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
							Connecting...
						{:else}
							<Wallet class="h-4 w-4 mr-2" />
							Connect Wallet
						{/if}
					</button>
				{/if}
				
				<!-- Mobile menu button -->
				<button
					onclick={() => isMenuOpen = !isMenuOpen}
					class="md:hidden inline-flex items-center justify-center p-2 rounded-md text-secondary-600 hover:text-secondary-900 hover:bg-secondary-100"
					aria-label="Toggle mobile menu"
				>
					<svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
						<path class={isMenuOpen ? 'hidden' : 'inline-flex'} stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
						<path class={isMenuOpen ? 'inline-flex' : 'hidden'} stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
		</div>
	</div>
	
	<!-- Mobile Navigation -->
	{#if isMenuOpen}
		<div class="md:hidden">
			<div class="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white border-t border-secondary-200">
                {#each navItems as item}
                    <a
                        href={item.href}
                        class="flex items-center px-3 py-2 rounded-md text-base font-medium transition-colors duration-200
                            {$page.url.pathname === item.href 
                                ? 'text-primary-600 bg-primary-50' 
                                : 'text-secondary-700 hover:text-primary-600 hover:bg-primary-50'}"
                    >
                        {#if item.icon}
                            <item.icon class="h-5 w-5 mr-3" />
                        {/if}
                        {item.label}
                    </a>
                {/each}
			</div>
		</div>
	{/if}
</nav>
