// frontend/src/routes/leaderboard/+page.svelte
<script lang="ts">
	import { Trophy, Medal, Award, Users, TrendingUp, Filter } from 'lucide-svelte';
	
	// Mock data - replace with actual data from blockchain
	let companies = $state([
		{
			id: 1,
			name: 'EcoTech Solutions',
			credits: 15420,
			actions: 89,
			badges: 5,
			rank: 1,
			change: '+2'
		},
		{
			id: 2,
			name: 'GreenCorp Industries',
			credits: 12850,
			actions: 76,
			badges: 4,
			rank: 2,
			change: '+1'
		},
		{
			id: 3,
			name: 'Sustainable Future Ltd',
			credits: 11200,
			actions: 68,
			badges: 4,
			rank: 3,
			change: '-1'
		},
		{
			id: 4,
			name: 'Climate Action Co',
			credits: 9850,
			actions: 54,
			badges: 3,
			rank: 4,
			change: '+3'
		},
		{
			id: 5,
			name: 'EcoVenture Partners',
			credits: 9200,
			actions: 51,
			badges: 3,
			rank: 5,
			change: '-2'
		},
		{
			id: 6,
			name: 'GreenTech Innovations',
			credits: 8750,
			actions: 48,
			badges: 3,
			rank: 6,
			change: '+1'
		},
		{
			id: 7,
			name: 'Sustainable Systems',
			credits: 8200,
			actions: 45,
			badges: 2,
			rank: 7,
			change: '+2'
		},
		{
			id: 8,
			name: 'EcoVision Group',
			credits: 7850,
			actions: 43,
			badges: 2,
			rank: 8,
			change: '-1'
		},
		{
			id: 9,
			name: 'GreenPath Enterprises',
			credits: 7200,
			actions: 40,
			badges: 2,
			rank: 9,
			change: '+1'
		},
		{
			id: 10,
			name: 'Climate Solutions Inc',
			credits: 6800,
			actions: 38,
			badges: 2,
			rank: 10,
			change: '-2'
		}
	]);
	
	let currentUser = $state({
		name: 'Your Company',
		credits: 2450,
		actions: 28,
		badges: 3,
		rank: 12,
		change: '+1'
	});
	
	let filterPeriod = $state('all');
	let filterOptions = ['all', 'month', 'week', 'day'];
	
	function getRankIcon(rank: number) {
		switch (rank) {
			case 1:
				return Trophy;
			case 2:
				return Medal;
			case 3:
				return Award;
			default:
				return null;
		}
	}
	
	function getRankColor(rank: number) {
		switch (rank) {
			case 1:
				return 'bg-yellow-100 text-yellow-800';
			case 2:
				return 'bg-gray-100 text-gray-800';
			case 3:
				return 'bg-amber-100 text-amber-800';
			default:
				return 'bg-secondary-100 text-secondary-800';
		}
	}
</script>

<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
	<!-- Header -->
	<div class="mb-8">
		<div class="flex items-center justify-between">
			<div>
				<h1 class="text-3xl font-bold text-secondary-900 mb-2">Leaderboard</h1>
				<p class="text-secondary-600">See how your company ranks in sustainability efforts</p>
			</div>
			<div class="flex items-center space-x-4">
				<select 
					bind:value={filterPeriod}
					class="bg-white border border-secondary-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
				>
					{#each filterOptions as option}
						<option value={option}>
							{option === 'all' ? 'All Time' : 
							 option === 'month' ? 'This Month' :
							 option === 'week' ? 'This Week' : 'Today'}
						</option>
					{/each}
				</select>
			</div>
		</div>
	</div>
	
	<!-- Current User Card -->
	<div class="card mb-8 bg-gradient-to-r from-primary-50 to-secondary-50 border-primary-200">
		<div class="flex items-center justify-between">
			<div class="flex items-center space-x-4">
				<div class="flex-shrink-0">
					<div class="w-12 h-12 bg-primary-600 rounded-full flex items-center justify-center">
						<Users class="h-6 w-6 text-white" />
					</div>
				</div>
				<div>
					<h3 class="text-lg font-semibold text-secondary-900">{currentUser.name}</h3>
					<p class="text-sm text-secondary-600">Rank #{currentUser.rank}</p>
				</div>
			</div>
			<div class="flex items-center space-x-6">
				<div class="text-center">
					<p class="text-2xl font-bold text-primary-600">{currentUser.credits.toLocaleString()}</p>
					<p class="text-sm text-secondary-600">Credits</p>
				</div>
				<div class="text-center">
					<p class="text-2xl font-bold text-secondary-900">{currentUser.actions}</p>
					<p class="text-sm text-secondary-600">Actions</p>
				</div>
				<div class="text-center">
					<p class="text-2xl font-bold text-secondary-900">{currentUser.badges}</p>
					<p class="text-sm text-secondary-600">Badges</p>
				</div>
				<div class="flex items-center space-x-1">
					<TrendingUp class="h-4 w-4 text-green-600" />
					<span class="text-sm font-medium text-green-600">{currentUser.change}</span>
				</div>
			</div>
		</div>
	</div>
	
	<!-- Top 3 Podium -->
	<div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
		{#each companies.slice(0, 3) as company, index}
			<div class="card {index === 0 ? 'md:order-2' : index === 1 ? 'md:order-1' : 'md:order-3'}">
				<div class="text-center">
					<div class="flex justify-center mb-4">
						{#if getRankIcon(company.rank)}
							<div class="w-16 h-16 {getRankColor(company.rank)} rounded-full flex items-center justify-center">
								<svelte:component this={getRankIcon(company.rank)} class="h-8 w-8" />
							</div>
						{/if}
					</div>
					<h3 class="text-xl font-bold text-secondary-900 mb-2">{company.name}</h3>
					<p class="text-3xl font-bold text-primary-600 mb-2">{company.credits.toLocaleString()}</p>
					<p class="text-sm text-secondary-600 mb-4">Carbon Credits</p>
					<div class="flex justify-center space-x-4 text-sm">
						<span class="text-secondary-600">{company.actions} actions</span>
						<span class="text-secondary-600">{company.badges} badges</span>
					</div>
					<div class="flex items-center justify-center mt-2">
						<TrendingUp class="h-4 w-4 text-green-600 mr-1" />
						<span class="text-sm font-medium text-green-600">{company.change}</span>
					</div>
				</div>
			</div>
		{/each}
	</div>
	
	<!-- Full Leaderboard Table -->
	<div class="card">
		<h3 class="text-lg font-semibold text-secondary-900 mb-6">Complete Rankings</h3>
		
		<div class="overflow-x-auto">
			<table class="min-w-full divide-y divide-secondary-200">
				<thead class="bg-secondary-50">
					<tr>
						<th class="px-6 py-3 text-left text-xs font-medium text-secondary-500 uppercase tracking-wider">
							Rank
						</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-secondary-500 uppercase tracking-wider">
							Company
						</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-secondary-500 uppercase tracking-wider">
							Credits
						</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-secondary-500 uppercase tracking-wider">
							Actions
						</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-secondary-500 uppercase tracking-wider">
							Badges
						</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-secondary-500 uppercase tracking-wider">
							Change
						</th>
					</tr>
				</thead>
				<tbody class="bg-white divide-y divide-secondary-200">
					{#each companies as company}
						<tr class="hover:bg-secondary-50">
							<td class="px-6 py-4 whitespace-nowrap">
								<div class="flex items-center">
									<span class="badge {getRankColor(company.rank)}">
										#{company.rank}
									</span>
								</div>
							</td>
							<td class="px-6 py-4 whitespace-nowrap">
								<div class="flex items-center">
									<div class="w-8 h-8 bg-primary-100 rounded-full flex items-center justify-center mr-3">
										<Users class="h-4 w-4 text-primary-600" />
									</div>
									<div class="text-sm font-medium text-secondary-900">
										{company.name}
									</div>
								</div>
							</td>
							<td class="px-6 py-4 whitespace-nowrap text-sm text-secondary-900">
								{company.credits.toLocaleString()}
							</td>
							<td class="px-6 py-4 whitespace-nowrap text-sm text-secondary-900">
								{company.actions}
							</td>
							<td class="px-6 py-4 whitespace-nowrap text-sm text-secondary-900">
								{company.badges}
							</td>
							<td class="px-6 py-4 whitespace-nowrap">
								<div class="flex items-center">
									<TrendingUp class="h-4 w-4 text-green-600 mr-1" />
									<span class="text-sm font-medium text-green-600">{company.change}</span>
								</div>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</div>
</div>

// frontend-react/src/pages/Leaderboard.tsx
import { useEffect, useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Loader2, Trophy, Sparkles, Crown, Medal } from 'lucide-react';
import { useUser } from '../contexts/UserContext';
import { useBlockchain } from '../hooks/useBlockchain';
import { useNotifications } from '../contexts/NotificationContext';
import { api } from '../lib/services/api';
import { ethers } from 'ethers';

interface LeaderboardEntry {
    rank: number;
    company: string; // wallet address
    totalCredits: bigint;
    reputationScore: bigint;
    companyName?: string;
    totalActions?: number;
    verified?: boolean;
}

export function Leaderboard() {
    const [entries, setEntries] = useState<LeaderboardEntry[]>([]);
    const [loading, setLoading] = useState(true);
    const [period, setPeriod] = useState<'weekly' | 'monthly' | 'all-time'>('all-time');
    const { user } = useUser();
    const { getTopCompanies, getCompanyRank } = useBlockchain();
    const { addNotification } = useNotifications();

    const loadLeaderboard = useCallback(async () => {
        setLoading(true);
        try {
            // Try blockchain contract first
            try {
                const topCompanies = await getTopCompanies(100);
                if (topCompanies && topCompanies.length > 0) {
                    // Map blockchain data to our format
                    const mappedEntries: LeaderboardEntry[] = topCompanies.map((entry: any, index: number) => ({
                        rank: Number(entry.rank) || index + 1,
                        company: entry.company,
                        totalCredits: entry.totalCredits,
                        reputationScore: entry.reputationScore,
                        companyName: undefined, // Will fetch from backend if needed
                        totalActions: 0,
                        verified: false
                    }));

                    // Try to enrich with backend data for company names
                    try {
                        const backendResponse = await api.getLeaderboard('ALL_TIME');
                        const backendMap = new Map(
                            (backendResponse || []).map((e: any) => [e.company?.walletAddress, e])
                        );

                        const enrichedEntries = mappedEntries.map(entry => {
                            const backendData = backendMap.get(entry.company);
                            return {
                                ...entry,
                                companyName: backendData?.company?.name || `${entry.company.slice(0, 6)}...${entry.company.slice(-4)}`,
                                totalActions: backendData?.totalActions || 0,
                                verified: backendData?.company?.verified || false
                            };
                        });

                        setEntries(enrichedEntries);
                        setLoading(false);
                        return;
                    } catch (backendError) {
                        console.warn('Failed to enrich with backend data, using blockchain data only:', backendError);
                        // Use blockchain data without backend enrichment
                    }
                    
                    // If backend enrichment failed, use blockchain data as-is
                    setEntries(mappedEntries);
                    setLoading(false);
                    return;
                }
            } catch (blockchainError) {
                console.warn('Failed to load from blockchain, falling back to backend:', blockchainError);
            }

            // Fallback to backend API
            const periodMap: Record<string, string> = {
                'weekly': 'WEEKLY',
                'monthly': 'MONTHLY',
                'all-time': 'ALL_TIME'
            };
            const response = await api.getLeaderboard(periodMap[period]);
            const mappedEntries: LeaderboardEntry[] = (response || []).map((entry: any, index: number) => ({
                rank: entry.rank || index + 1,
                company: entry.company?.walletAddress || entry.companyId || '',
                totalCredits: BigInt(entry.totalCredits || 0),
                reputationScore: BigInt(0),
                companyName: entry.company?.name || 'Unknown',
                totalActions: entry.totalActions || 0,
                verified: entry.company?.verified || false
            }));
            setEntries(mappedEntries);
        } catch (error) {
            console.error('Failed to load leaderboard:', error);
            addNotification('error', 'Failed to load leaderboard');
        } finally {
            setLoading(false);
        }
    }, [period, getTopCompanies, addNotification]);

    useEffect(() => {
        loadLeaderboard();
    }, [loadLeaderboard]);

    const getRankColor = (rank: number) => {
        if (rank === 1) return 'text-yellow-600';
        if (rank === 2) return 'text-gray-400';
        if (rank === 3) return 'text-orange-600';
        return 'text-secondary-600';
    };

    const getRankBg = (rank: number) => {
        if (rank === 1) return 'bg-yellow-100';
        if (rank === 2) return 'bg-gray-100';
        if (rank === 3) return 'bg-orange-100';
        return 'bg-secondary-50';
    };

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <motion.div 
                className="flex justify-between items-center mb-8"
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
            >
                <div>
                    <div className="flex items-center gap-3 mb-2">
                        <motion.div
                            animate={{ rotate: [0, 10, -10, 0] }}
                            transition={{ duration: 2, repeat: Infinity, repeatDelay: 3 }}
                        >
                            <Sparkles className="h-8 w-8 text-primary-600" />
                        </motion.div>
                        <h1 className="text-4xl font-bold gradient-text">Leaderboard</h1>
                    </div>
                    <p className="mt-2 text-secondary-600 text-lg">
                        Top performing companies in carbon credit generation.
                    </p>
                </div>

                <motion.select
                    value={period}
                    onChange={(e) => setPeriod(e.target.value as 'weekly' | 'monthly' | 'all-time')}
                    className="px-4 py-2 border border-secondary-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 bg-white shadow-sm"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                >
                    <option value="weekly">This Week</option>
                    <option value="monthly">This Month</option>
                    <option value="all-time">All Time</option>
                </motion.select>
            </motion.div>

            {/* Top 3 Podium */}
            {!loading && entries.length >= 3 && (
                <div className="grid grid-cols-3 gap-4 mb-8">
                    {/* 2nd Place */}
                    <motion.div 
                        className="order-1"
                        initial={{ opacity: 0, x: -50, y: 50 }}
                        animate={{ opacity: 1, x: 0, y: 0 }}
                        transition={{ delay: 0.2, duration: 0.6, type: "spring" }}
                    >
                        <div className="card card-hover p-6 text-center relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-gray-400 to-gray-500"></div>
                            <motion.div 
                                className={`w-16 h-16 mx-auto mb-3 rounded-full ${getRankBg(2)} flex items-center justify-center shadow-lg`}
                                animate={{ y: [0, -5, 0] }}
                                transition={{ duration: 2, repeat: Infinity }}
                            >
                                <Medal className={getRankColor(2)} size={32} />
                            </motion.div>
                            <div className="text-2xl font-bold text-secondary-400 mb-1">2nd</div>
                            <h3 className="font-semibold text-secondary-900 mb-2">{entries[1].companyName || `${entries[1].company.slice(0, 6)}...${entries[1].company.slice(-4)}`}</h3>
                            <p className="text-lg font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">{ethers.formatEther(entries[1].totalCredits)} Credits</p>
                        </div>
                    </motion.div>

                    {/* 1st Place */}
                    <motion.div 
                        className="order-2"
                        initial={{ opacity: 0, y: -50, scale: 0.8 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        transition={{ delay: 0.1, duration: 0.6, type: "spring" }}
                    >
                        <div className="card p-6 text-center relative overflow-hidden border-2 border-yellow-400 shadow-xl bg-gradient-to-br from-yellow-50 to-amber-50">
                            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-yellow-400 via-yellow-500 to-yellow-400"></div>
                            <motion.div 
                                className={`w-20 h-20 mx-auto mb-3 rounded-full ${getRankBg(1)} flex items-center justify-center shadow-xl relative`}
                                animate={{ 
                                    y: [0, -10, 0],
                                    rotate: [0, 5, -5, 0]
                                }}
                                transition={{ duration: 2, repeat: Infinity }}
                            >
                                <Crown className={getRankColor(1)} size={40} />
                                <motion.div
                                    className="absolute inset-0 rounded-full bg-yellow-400 opacity-20"
                                    animate={{ scale: [1, 1.2, 1] }}
                                    transition={{ duration: 2, repeat: Infinity }}
                                />
                            </motion.div>
                            <div className="text-3xl font-bold bg-gradient-to-r from-yellow-600 to-amber-600 bg-clip-text text-transparent mb-1">1st</div>
                            <h3 className="font-semibold text-secondary-900 mb-2 text-lg">{entries[0].companyName || `${entries[0].company.slice(0, 6)}...${entries[0].company.slice(-4)}`}</h3>
                            <p className="text-xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">{ethers.formatEther(entries[0].totalCredits)} Credits</p>
                        </div>
                    </motion.div>

                    {/* 3rd Place */}
                    <motion.div 
                        className="order-3"
                        initial={{ opacity: 0, x: 50, y: 50 }}
                        animate={{ opacity: 1, x: 0, y: 0 }}
                        transition={{ delay: 0.3, duration: 0.6, type: "spring" }}
                    >
                        <div className="card card-hover p-6 text-center relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-orange-400 to-orange-500"></div>
                            <motion.div 
                                className={`w-16 h-16 mx-auto mb-3 rounded-full ${getRankBg(3)} flex items-center justify-center shadow-lg`}
                                animate={{ y: [0, -5, 0] }}
                                transition={{ duration: 2, repeat: Infinity, delay: 0.5 }}
                            >
                                <Medal className={getRankColor(3)} size={32} />
                            </motion.div>
                            <div className="text-2xl font-bold text-orange-600 mb-1">3rd</div>
                            <h3 className="font-semibold text-secondary-900 mb-2">{entries[2].companyName || `${entries[2].company.slice(0, 6)}...${entries[2].company.slice(-4)}`}</h3>
                            <p className="text-lg font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">{ethers.formatEther(entries[2].totalCredits)} Credits</p>
                        </div>
                    </motion.div>
                </div>
            )}

            {/* Full Leaderboard Table */}
            {loading ? (
                <motion.div 
                    className="flex justify-center py-12"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                >
                    <Loader2 size={40} className="animate-spin text-primary-600" />
                </motion.div>
            ) : entries.length === 0 ? (
                <motion.div 
                    className="text-center py-12 card"
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.5 }}
                >
                    <motion.div
                        animate={{ y: [0, -10, 0] }}
                        transition={{ duration: 2, repeat: Infinity }}
                    >
                        <Trophy size={48} className="mx-auto text-secondary-400 mb-4" />
                    </motion.div>
                    <h3 className="text-lg font-medium text-secondary-900">No data available</h3>
                    <p className="text-secondary-500 mt-1">Check back later for rankings</p>
                </motion.div>
            ) : (
                <motion.div 
                    className="card overflow-hidden"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.4, duration: 0.5 }}
                >
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-secondary-200">
                            <thead className="bg-gradient-to-r from-secondary-50 to-secondary-100">
                                <tr>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-secondary-600 uppercase tracking-wider">Rank</th>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-secondary-600 uppercase tracking-wider">Company</th>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-secondary-600 uppercase tracking-wider">Credits</th>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-secondary-600 uppercase tracking-wider">Actions</th>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-secondary-600 uppercase tracking-wider">Avg/Action</th>
                                </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-secondary-200">
                                {entries.map((entry, index) => {
                                    const isCurrentUser = user?.walletAddress?.toLowerCase() === entry.company.toLowerCase();
                                    const creditsFormatted = ethers.formatEther(entry.totalCredits);
                                    return (
                                        <motion.tr
                                            key={entry.company}
                                            className={`${isCurrentUser ? 'bg-gradient-to-r from-primary-50 to-primary-100/50' : 'hover:bg-secondary-50'} transition-colors`}
                                            initial={{ opacity: 0, x: -20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: index * 0.05 + 0.5, duration: 0.3 }}
                                            whileHover={{ scale: 1.01, x: 5 }}
                                        >
                                            <td className="px-6 py-4 whitespace-nowrap">
                                                <div className={`flex items-center gap-2 ${getRankColor(entry.rank)} font-bold text-lg`}>
                                                    {entry.rank <= 3 && <Trophy size={20} />}
                                                    #{entry.rank}
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap">
                                                <div className="flex items-center gap-2">
                                                    <span className="font-medium text-secondary-900">
                                                        {entry.companyName || `${entry.company.slice(0, 6)}...${entry.company.slice(-4)}`}
                                                    </span>
                                                    {entry.verified && (
                                                        <motion.span 
                                                            className="px-2 py-0.5 text-xs bg-gradient-to-r from-green-100 to-emerald-100 text-green-800 rounded-full border border-green-200"
                                                            initial={{ scale: 0 }}
                                                            animate={{ scale: 1 }}
                                                            transition={{ delay: index * 0.05 + 0.6 }}
                                                        >
                                                            ✓ Verified
                                                        </motion.span>
                                                    )}
                                                    {isCurrentUser && (
                                                        <motion.span 
                                                            className="px-2 py-0.5 text-xs bg-gradient-to-r from-primary-100 to-primary-200 text-primary-800 rounded-full border border-primary-300"
                                                            initial={{ scale: 0 }}
                                                            animate={{ scale: 1 }}
                                                            transition={{ delay: index * 0.05 + 0.6 }}
                                                        >
                                                            You
                                                        </motion.span>
                                                    )}
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">
                                                {parseFloat(creditsFormatted).toFixed(2)}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-secondary-500">
                                                {entry.totalActions || 0}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-secondary-500">
                                                {entry.totalActions && entry.totalActions > 0 
                                                    ? (parseFloat(creditsFormatted) / entry.totalActions).toFixed(1) 
                                                    : '0'}
                                            </td>
                                        </motion.tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </motion.div>
            )}
        </div>
    );
}
